// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-5rpX3IBv8cY3_jLoN0z7TU0vgHEdAU4',
    appId: '1:651879327595:web:9ff9d875af37c841c54e2e',
    messagingSenderId: '651879327595',
    projectId: 'taxi-app-337b4',
    authDomain: 'taxi-app-337b4.firebaseapp.com',
    storageBucket: 'taxi-app-337b4.firebasestorage.app',
    measurementId: 'G-415QS7KQ2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8yLp2LhuNNzHZkT0QGarGxpgmhg2cKU',
    appId: '1:651879327595:android:6fef33330f722d97c54e2e',
    messagingSenderId: '651879327595',
    projectId: 'taxi-app-337b4',
    storageBucket: 'taxi-app-337b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIj5o6jUYbQpZzMdgE5DbO2hC1MhjftWg',
    appId: '1:651879327595:ios:3167c14070f2b806c54e2e',
    messagingSenderId: '651879327595',
    projectId: 'taxi-app-337b4',
    storageBucket: 'taxi-app-337b4.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIj5o6jUYbQpZzMdgE5DbO2hC1MhjftWg',
    appId: '1:651879327595:ios:3167c14070f2b806c54e2e',
    messagingSenderId: '651879327595',
    projectId: 'taxi-app-337b4',
    storageBucket: 'taxi-app-337b4.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-5rpX3IBv8cY3_jLoN0z7TU0vgHEdAU4',
    appId: '1:651879327595:web:2b55815680c85bcac54e2e',
    messagingSenderId: '651879327595',
    projectId: 'taxi-app-337b4',
    authDomain: 'taxi-app-337b4.firebaseapp.com',
    storageBucket: 'taxi-app-337b4.firebasestorage.app',
    measurementId: 'G-WR3B64KFQ1',
  );
}
